CREATE TABLE `cars`.`clients` ( `Id` INT(10) NOT NULL AUTO_INCREMENT , `Name` VARCHAR(30) NOT NULL , `Address` VARCHAR(50) NOT NULL , `Email` VARCHAR(50) NOT NULL , PRIMARY KEY (`Id`)) ENGINE = InnoDB;

CREATE TABLE `cars`.`invoices` ( `Id` INT(10) NOT NULL AUTO_INCREMENT , `ClientId` INT(10) NOT NULL , `Type` TINYINT(1) NOT NULL , `Cost` FLOAT(20) NOT NULL , PRIMARY KEY (`Id`)) ENGINE = InnoDB;

ALTER TABLE `invoices` ADD FOREIGN KEY (`ClientId`) REFERENCES `clients`(`Id`) ON DELETE RESTRICT ON UPDATE RESTRICT;